
spring:
  application:
    name: tasks
  datasource:
    url: jdbc:mysql://localhost:3306/task_manger
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
