server:
  port: 8080

spring:
  application:
    name: GatewayApi
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/employee/**
            - Path=/manager/**
            - Path=/user/**

        - id: tasks
          uri: lb://tasks
          predicates:
            - Path=/tasks/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
