server:
  port: 8080

spring:
  application:
    name: GatewayApi
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/employee/**, /manager/**, /user/**
        - id: tasks
          uri: lb://tasks
          predicates:
            - Path=/tasks/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
add-to-simple-url-handler-mapping: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
